version: '3.8'

volumes:
  mongo_vol:

networks:
  produto_net:
    driver: bridge

services:

  mongodb:
    image: mongo:${TAG}
    ports:
    - 27017:27017
    networks:
     - produto_net
    volumes:
     - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
     - 8081:8081
    networks:
     - produto_net
    depends_on:
     - mongodb
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:example@mongodb:27017
