version: '3.8'

volumes:
  mdb_vol:

networks:
  new-net-mdb:
    driver: bridge

services:

  mariadb:
    image: mariadb
    ports:
    - 3306:3306
    networks:
     - new-net-mdb
    volumes:
     - mdb_vol:/var/libmysql
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: senha123456
      MARIADB_ROOT_PASSWORD: senha123456

  phpmyadmin:
    image: phpmyadmin
    ports:
     - 8080:80
    networks:
     - new-net-mdb
    environment:
      PMA_HOST: mariadb