version: '3.8'

volumes:
  pg_vol:

networks:
  net-postgre:
    driver: bridge

services:

  redis:
    image: redis:7.0.8
    ports:
    - 5432:5432
    networks:
     - net-postgre
    volumes:
     - pg_vol:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: senha123456
      POSTGRES_USER: root

  pgadmin:
    image: rediscommander/redis-commander
    ports:
     - 8080:80
    networks:
     - net-postgre
    environment:
      PGADMIN_DEFAULT_PASSWORD: senha654321
      PGADMIN_DEFAULT_EMAIL: tercio@teste.com