version: '3.8'

volumes:
  redis_vol:

networks:
  net-redis:
    driver: bridge

services:

  redis:
    image: redis:7.0.8
    hostname: redis_test1
    container_name: redis_my
    networks:
     - net-redis
    volumes:
     - redis_vol:/var/lib/redisdb

  redis-commander:
    image: rediscommander/redis-commander
    ports:
     - 8081:8081
    networks:
     - net-redis
    environment:
      REDIS_HOSTS: local:redis_test1:6379